version: '3.9'
services:
  db:
    image: 'postgres:14-alpine'
    container_name: phone_book_db
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: phone_book_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
  adminer:
    image: adminer
    container_name: phone_book_adminer 
    restart: always
    ports:
      - '8080:8080'
  web:
    build: .
    container_name: phone_book_web
    command: mix phx.server
    restart: always
    environment:
      MIX_ENV: dev
      PORT: 4000
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    depends_on:
      - db
      - adminer
volumes:
  db-data: